name: Mirror to Organization Repo

on:
  push:
    branches:
      - main

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to PharmaForest
        env:
          ORG_REPO: https://github.com/PharmaForest/SASPACer.git
          PAT_TOKEN: ${{ secrets.TOKEN }}   # ← 登録済みのPAT secretを使用
        run: |
          git remote add mirror https://x-access-token:${PAT_TOKEN}@github.com/PharmaForest/SASPACer.git
          git push --mirror mirror
